### ISSUE TITLE
Add factui to the list

### ISSUE THREAD

**Issue by nrfm** [simongray/clojure-graph-resources#10]
[https://github.com/arachne-framework/factui](https://github.com/arachne-framework/factui)

> FactUI is a library for efficiently rendering user interfaces declaratively, based on a tuple-oriented data store.

It uses a datomic-like syntax for rules declaration. and clara-rules underneath. So it feels like datascript + re-posh + rules.

I used it in a project a while back and it worked great with reagent. 
Seems abandoned but some great code and ideas to explore in there.

**Comment by simongray** [comment]
I think it looks interesting and I did consider it, but development seems to have stopped in 2018.
