### ISSUE TITLE
Denormalized data structures

### ISSUE THREAD

**Issue by lilactown** [simongray/clojure-graph-resources#2]
These are more in the realm of storing data in a denormalized fashion, rather than doing operations on graphs, but still relevant IMO.

https://github.com/stuartsierra/mapgraph (archived but still used / relevant)

https://github.com/keechma/keechma-entitydb

https://github.com/den1k/subgraph a fork of mapgraph that interops with re-frame

There are probably others in this same fashion, those are just the 3 I know off the top of my head.

**Comment by simongray** [comment]
Thanks. Added in b5511b52753180ae38e53b5acac041d694428a71
