### ISSUE TITLE
Graph query resources

### ISSUE THREAD

**Issue by lilactown** [simongray/clojure-graph-resources#3]
EDN query language (EQL) is a GraphQL-like language specification: https://github.com/edn-query-language/eql

Pathom is a library which helps with implementing services that provide EQL APIs: https://github.com/wilkerlucio/pathom

Speaking of GraphQL, lacinia is a popular library for implementing GraphQL services: https://github.com/walmartlabs/lacinia

**Comment by simongray** [comment]
Thanks. Added these three in 4b534cb7fbda487d727706ff7ad4985785d05fdd
