### ISSUE TITLE
Graph query benchmarking

### ISSUE THREAD

**Issue by refset** [simongray/clojure-graph-resources#4]
The Crux repository maintains a comparative query benchmarking project, most notably including WatDiv ("Waterloo SPARQL Diversity Test Suite") which is an RDF-based suite of  "subgraph matching" stress tests that have been adapted to run using Datalog and Cypher also:
https://github.com/juxt/crux/tree/master/crux-bench

The benchmark results are not currently published but the project can be run independently and could be extended to cover the other databases listed.

**Comment by simongray** [comment]
I think the benchmarks could be interesting, but the benchmarking library itself feels a bit out of place on this list.
