### ISSUE TITLE
Consider plumatic/graph

### ISSUE THREAD

**Issue by rlander** [simongray/clojure-graph-resources#7]
First of all, great idea! Second, I’d like to suggest one of my favorite clj libs, Plumatic Graph.

From Plumbing’s [readme](https://github.com/plumatic/plumbing) :

> Graph is a simple and declarative way to specify a structured computation, which is easy to analyze, change, compose, and monitor.

Although it is mostly focused on DAGs to create stream graph computation models, IME it’s a very practical and useful lib.

**Comment by simongray** [comment]
Thanks! I was in need of such a list myself, so I thought why not just start making it and have other people suggest me things :-P

Added plumbing in 3f49baeb8b9e53f1f09bc84c7d0e37a3e00801b7
